// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lozvfrbykmojrwyzxrdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvenZmcmJ5a21vanJ3eXp4cmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTk5MjgsImV4cCI6MjA3MTAzNTkyOH0.-_Mh5w372xszdREE5Buo0ovfPvTzHR5_sBueT0wxsy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});